# Generated by Django 2.2.10 on 2020-12-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
