# Generated by Django 2.2.10 on 2020-12-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.TextField(default='admin'),
        ),
    ]
