# Generated by Django 2.2.10 on 2020-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='true_choice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
